### ISSUE TITLE
Is 0.7.0 missing from master?

### ISSUE THREAD

**Issue by glasserc** [mozilla-extensions/normandy-devtools#10]
I tried to build my own web extension and it didn't work (I got a giant red frowny face). But running 0.7.0 from the releases page seems to work fine.

**Comment by mythmon** [comment]
Yes, 0.7.0 was missing from master. I made the release and forgot to `git push`. I just pushed, so it should work again.

FYI, the giant red frowny face is a "React error boundary". It is a replacement for the white screen of death you so often get when thing go terribly wrong. It was #9 and caused by the Normandy server v3 API changing schemas.
