### ISSUE TITLE
No error message is displayed after creating a Heartbeat recipe on Normandy Devtools with invalid URLs 

### ISSUE THREAD

**Issue by SoftVision-SimonaRosu** [mozilla-extensions/normandy-devtools#618]
[Affected versions]:
 - Firefox Release 82.0.3 (Build ID: 20201108180448)

[Affected Platforms]:
 - Windows 10 x64

[Prerequisites]:
- Have the Firefox browser installed.
- Have the  [Normandy Devtools V2.2.0 addon](https://github.com/mozilla-extensions/normandy-devtools/releases) installed.
- Have VPN access to the staging environment.

[Steps to reproduce]:
1. Open the Normandy Devtools and choose the Stage environment.
2. Set up a heartbeat recipe ([link to set-up](https://docs.google.com/document/d/1mDhTv0syfgBOggHgbGZwckTS9gFRsI7-lSDUqHsjvUY/edit))  targeting your browser using invalid “Learn More Url” and “Post Answer Url” URLs.
3. Click on the “Save” button.
4. Observe the behavior.

[Expected result]:
 - An error message is displayed stating that the URLs must be valid.

[Actual result]:
 - The recipe is successfully created and no error message is displayed.

[Notes]:
- Attached a screen recording of the issue.

![HearbeatRecipe_NoErrorMessage](https://user-images.githubusercontent.com/50919288/99397902-55189780-28ec-11eb-9663-8a8117488aad.gif)

**Comment by mythmon** [comment]
It isn't the job of NDT to validate this data, it is the job of Normandy Server. If we were to fix the problem here, it would still allow other clients to make the same mistakes, which isn't right. https://github.com/mozilla/normandy would be the right place to file this.

That being said, I don't think that this is a bug that we want to fix. I think that the definition of what is or is not a valid URL for the case of Heartbeat is ill defined, and it hasn't been a problem in the years that Heartbeat has been running.
